version: "3.1"

services: 
  motorbd: 
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=root
    volumes: 
      - "./sql:/docker-entrypoint-initdb.d"
      - "./database:/var/lib/postgresql/data"
    
    

  gestionbd: 
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: 
      - "80:80"
    depends_on:
      - motorbd

  shellbd: 
    image: ubuntu:alpine
    


