version: "3.1"
services: 
  motorbd: 
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=root
    
    volumes: 
      - "./sql:/docker-entrypoint-initdb.d"
      - "./database:/var/lib/postgresql/data"
    networks:
      network1: 
        aliases: 
          - network1_host



  gestionbd: 
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: 
      - "80:80"
    depends_on:
      - motorbd
    networks: 
      network1: 
        aliases: 
          - network1_host
      network2: 
        aliases: 
          - network2_host
    

  shellbd: 
    image: alpine:latest
    entrypoint: /bin/sh
    stdin_open: true
    tty: true

    ports: 
      - "1500:80"
    networks:
      network2: 
        aliases: 
          - network2_host
  
networks: 
  network1: 
    driver: bridge 
    ipam:
      driver: default
  network2: 
    driver: bridge
    ipam: 
      driver: default
    

    
